"""Insight — a forward-looking prediction generated by the prediction engine.

Each row is one actionable prediction for a project: a cost-overrun forecast,
a rate-limit exhaustion ETA, or a model-drift alert. The prediction engine
(services/predictions/) upserts rows keyed by (project_id, dedup_key) so a
recurring run refreshes an open insight rather than creating duplicates.

Unlike spans, this table is small (a handful of open rows per project) and is
not partitioned.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal
from typing import Any, Optional

from sqlalchemy import ForeignKey, Numeric, String, Text, text
from sqlalchemy import TIMESTAMP
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from whyllm_api.database import Base


class Insight(Base):
    __tablename__ = "insights"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
    )
    # Denormalized — avoids a join to projects on the dashboard read path.
    org_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)

    # ---- Classification ------------------------------------------------------
    # cost_forecast | rate_limit_eta | model_drift
    type: Mapped[str] = mapped_column(String(50), nullable=False)
    # info | warning | critical
    severity: Mapped[str] = mapped_column(
        String(20), server_default=text("'info'"), nullable=False
    )
    # open | acknowledged | resolved
    status: Mapped[str] = mapped_column(
        String(20), server_default=text("'open'"), nullable=False
    )

    # ---- Content -------------------------------------------------------------
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    # Structured payload — the numbers behind the prediction (projections,
    # baselines, ETAs). Schema varies by `type`; see each analyser.
    detail: Mapped[dict[str, Any]] = mapped_column(
        JSONB, server_default=text("'{}'"), nullable=False
    )

    # ---- Engine bookkeeping --------------------------------------------------
    # Stable key for upsert — (project_id, dedup_key) is unique.
    dedup_key: Mapped[str] = mapped_column(String(255), nullable=False)
    # 0.00-1.00 — the engine's confidence in this prediction
    confidence: Mapped[Optional[Decimal]] = mapped_column(Numeric(3, 2), nullable=True)
    # When the predicted event is expected to occur (NULL if not time-bound)
    predicted_for: Mapped[Optional[datetime]] = mapped_column(
        TIMESTAMP(timezone=True), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), server_default=text("NOW()"), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), server_default=text("NOW()"), nullable=False
    )
